/**
 * @description ClickCoin 분석 대상 종목 리스트 (v102 최적화 반영)
 * 시가총액 상위 100개 가상자산
 */
export const STOCK_LIST = [
  { symbol: "BTC-USD", name: "Bitcoin" },
  { symbol: "ETH-USD", name: "Ethereum" },
  { symbol: "USDT-USD", name: "Tether" },
  { symbol: "BNB-USD", name: "BNB" },
  { symbol: "XRP-USD", name: "XRP" },
  { symbol: "USDC-USD", name: "USDC" },
  { symbol: "SOL-USD", name: "Solana" },
  { symbol: "TRX-USD", name: "TRON" },
  { symbol: "DOGE-USD", name: "Dogecoin" },
  { symbol: "ADA-USD", name: "Cardano" },
  { symbol: "BCH-USD", name: "Bitcoin Cash" },
  { symbol: "LEO-USD", name: "UNUS SED LEO" },
  { symbol: "HYPE-USD", name: "Hyperliquid" },
  { symbol: "XMR-USD", name: "Monero" },
  { symbol: "LINK-USD", name: "Chainlink" },
  { symbol: "DAI-USD", name: "Dai" },
  { symbol: "XLM-USD", name: "Stellar" },
  { symbol: "PYUSD-USD", name: "PayPal USD" },
  { symbol: "HBAR-USD", name: "Hedera" },
  { symbol: "LTC-USD", name: "Litecoin" },
  { symbol: "AVAX-USD", name: "Avalanche" },
  { symbol: "ZEC-USD", name: "Zcash" },
  { symbol: "SHIB-USD", name: "Shiba Inu" },
  { symbol: "SUI-USD", name: "Sui" },
  { symbol: "TON-USD", name: "Toncoin" },
  { symbol: "CRO-USD", name: "Cronos" },
  { symbol: "DOT-USD", name: "Polkadot" },
  { symbol: "UNI-USD", name: "Uniswap" },
  { symbol: "MNT-USD", name: "Mantle" },
  { symbol: "TAO-USD", name: "Bittensor" },
  { symbol: "AAVE-USD", name: "Aave" },
  { symbol: "OKB-USD", name: "OKB" },
  { symbol: "PEPE-USD", name: "Pepe" },
  { symbol: "NEAR-USD", name: "NEAR Protocol" },
  { symbol: "ETC-USD", name: "Ethereum Classic" },
  { symbol: "ICP-USD", name: "Internet Computer" },
  { symbol: "ONDO-USD", name: "Ondo" },
  { symbol: "USDD-USD", name: "USDD" },
  { symbol: "POL-USD", name: "Polygon" },
  { symbol: "WLD-USD", name: "Worldcoin" },
  { symbol: "KCS-USD", name: "KuCoin Token" },
  { symbol: "ATOM-USD", name: "Cosmos" },
  { symbol: "ENA-USD", name: "Ethena" },
  { symbol: "KAS-USD", name: "Kaspa" },
  { symbol: "GT-USD", name: "GateToken" },
  { symbol: "FLR-USD", name: "Flare" },
  { symbol: "ALGO-USD", name: "Algorand" },
  { symbol: "QNT-USD", name: "Quant" },
  { symbol: "FIL-USD", name: "Filecoin" },
  { symbol: "MORPHO-USD", name: "Morpho" },
  { symbol: "APT-USD", name: "Aptos" },
  { symbol: "RENDER-USD", name: "Render" },
  { symbol: "XDC-USD", name: "XDC Network" },
  { symbol: "VET-USD", name: "VeChain" },
  { symbol: "ARB-USD", name: "Arbitrum" },
  { symbol: "NEXO-USD", name: "Nexo" },
  { symbol: "JUP-USD", name: "Jupiter" },
  { symbol: "TUSD-USD", name: "TrueUSD" },
  { symbol: "BONK-USD", name: "Bonk" },
  { symbol: "DCR-USD", name: "Decred" },
  { symbol: "EURC-USD", name: "EURC" },
  { symbol: "ZRO-USD", name: "LayerZero" },
  { symbol: "STX-USD", name: "Stacks" },
  { symbol: "SEI-USD", name: "Sei" },
  { symbol: "JST-USD", name: "JUST" },
  { symbol: "CAKE-USD", name: "PancakeSwap" },
  { symbol: "DASH-USD", name: "Dash" },
  { symbol: "XTZ-USD", name: "Tezos" },
  { symbol: "ETHFI-USD", name: "ether.fi" },
  { symbol: "CRV-USD", name: "Curve DAO Token" },
  { symbol: "FET-USD", name: "Artificial Intelligence" },
  { symbol: "KAIA-USD", name: "Kaia" },
  { symbol: "BTT-USD", name: "BitTorrent" },
  { symbol: "CHZ-USD", name: "Chiliz" },
  { symbol: "TIA-USD", name: "Celestia" },
  { symbol: "IMX-USD", name: "Immutable" },
  { symbol: "RUNE-USD", name: "THORChain" },
  { symbol: "MKR-USD", name: "Maker" },
  { symbol: "LDO-USD", name: "Lido DAO" },
  { symbol: "INJ-USD", name: "Injective" },
  { symbol: "BEAM-USD", name: "Beam" },
  { symbol: "THETA-USD", name: "Theta Network" },
  { symbol: "FLOW-USD", name: "Flow" },
  { symbol: "ASTR-USD", name: "Astar" },
  { symbol: "TWT-USD", name: "Trust Wallet Token" },
  { symbol: "WIF-USD", name: "dogwifhat" },
  { symbol: "FLOKI-USD", name: "Floki" },
  { symbol: "GALA-USD", name: "Gala" },
  { symbol: "GAS-USD", name: "Neo Gas" },
  { symbol: "NEO-USD", name: "Neo" },
  { symbol: "EOS-USD", name: "EOS" },
  { symbol: "IOTA-USD", name: "IOTA" },
  { symbol: "MANA-USD", name: "Decentraland" },
  { symbol: "SAND-USD", name: "The Sandbox" },
  { symbol: "AXS-USD", name: "Axie Infinity" },
  { symbol: "KAVA-USD", name: "Kava" },
  { symbol: "CFX-USD", name: "Conflu" },
  { symbol: "MINA-USD", name: "Mina" },
  { symbol: "STG-USD", name: "Stargate Finance" },
  { symbol: "EGLD-USD", name: "MultiversX" }
];
